name       : mdbook
version    : 0.3.5
release    : 4
source     :
    - https://github.com/rust-lang/mdBook/archive/v0.3.5.tar.gz : 73258ba3713004e06675ef2a1fbd3e7b48eb144db37c5ac1e2b96086b51a6e87
license    : MPL-2.0
component  : programming.tools
summary    : Create books from markdown files
description: |
    Create book from markdown files. Like Gitbook but implemented in Rust
networking : yes
builddeps  :
    - cargo
    - rust
build      : |
    cargo build %JOBS% --release
install    : |
    install -D -m 00755 target/release/mdbook $installdir/usr/bin/mdbook
