name       : mdbook
version    : 0.4.21
release    : 24
source     :
    - https://github.com/rust-lang/mdBook/archive/refs/tags/v0.4.21.tar.gz : 17385837070c6a312eae4717fe0bfdd259ce07b4b653b5c258b4389062df886d
homepage   : https://github.com/rust-lang/mdBook
license    : MPL-2.0
component  : programming.tools
summary    : Create books from markdown files
description: |
    mdBook is a command line tool to create book from markdown files. Like Gitbook but implemented in Rust.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build %JOBS% --release
install    : |
    install -Dm00755 target/release/mdbook $installdir/usr/bin/mdbook
