name       : mdbook
version    : 0.4.4
release    : 7
source     :
    - https://github.com/rust-lang/mdBook/archive/v0.4.4.tar.gz : eaf01085bd25e2efa07b561148afa5e3da3386e5f2c35b245961dc485562c154
homepage   : https://github.com/rust-lang/mdBook
license    : MPL-2.0
component  : programming.tools
summary    : Create books from markdown files
description: |
    mdBook is a command line tool to create book from markdown files. Like Gitbook but implemented in Rust.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build %JOBS% --release
install    : |
    install -Dm00755 target/release/mdbook $installdir/usr/bin/mdbook
