name       : mdbook
version    : 0.2.1
release    : 3
source     :
    - https://github.com/rust-lang-nursery/mdBook/archive/v0.2.1.tar.gz : 2d3d57120a082d973fded27ac1e9fb36078a1e24692ceebb887a11567552642d
license    : MPL-2.0
component  : programming.tools
summary    : Create books from markdown files
description: |
    Create book from markdown files. Like Gitbook but implemented in Rust
networking : yes
builddeps  :
    - cargo
    - rust
build      : |
    cargo build %JOBS% --release
install    : |
    install -D -m 00755 target/release/mdbook $installdir/usr/bin/mdbook
